// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qmxvarrqsioofadajlcd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFteHZhcnJxc2lvb2ZhZGFqbGNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyMzI3NDEsImV4cCI6MjA1NTgwODc0MX0.DotWqYiSItaL5KIx1-hXmitcLVdXcQ54mSg6C12Xs3M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);